server:
  port: 9000

spring:
  application:
    name: prabhu-eureka-client-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true